//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.PriceGroupCities = new HashSet<PriceGroupCity>();
            this.GroupModalCities = new HashSet<GroupModalCity>();
            this.GroupCustomDataPages = new HashSet<GroupCustomDataPage>();
        }
    
        public int idCity { get; set; }
        public string state { get; set; }
        public string name { get; set; }
        public int DDD { get; set; }
        public Nullable<int> idPriceGroupTV { get; set; }
        public Nullable<int> idPriceGroupFixo { get; set; }
        public Nullable<int> idPriceGroupBandaLarga { get; set; }
        public Nullable<int> idPriceGroupCombo { get; set; }
        public Nullable<int> idPriceGroupCelularPos { get; set; }
        public Nullable<int> idPriceGroupCelularPre { get; set; }
        public Nullable<int> idPriceGroupCelularControle { get; set; }
        public int idGroupHomePage { get; set; }
        public int idGroupMenu { get; set; }
        public int idGroupControlePage { get; set; }
        public int idGroupPosPago { get; set; }
    
        public virtual ICollection<PriceGroupCity> PriceGroupCities { get; set; }
        public virtual ICollection<GroupModalCity> GroupModalCities { get; set; }
        public virtual ICollection<GroupCustomDataPage> GroupCustomDataPages { get; set; }
    }
}
