//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Permission
    {
        public CMS_Permission()
        {
            this.CMS_Account = new HashSet<CMS_Account>();
        }
    
        public int idPermission { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<CMS_Account> CMS_Account { get; set; }
    }
}
