//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Account
    {
        public CMS_Account()
        {
            this.CMS_AccountLoginLog = new HashSet<CMS_AccountLoginLog>();
        }
    
        public int idAccount { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dtCreate { get; set; }
    
        public virtual ICollection<CMS_AccountLoginLog> CMS_AccountLoginLog { get; set; }
    }
}
