//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_AccountLoginLog
    {
        public int idAccountLoginLog { get; set; }
        public int idAccount { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime dtRegister { get; set; }
    
        public virtual CMS_Account CMS_Account { get; set; }
    }
}
