//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCustomData
    {
        public GroupCustomData()
        {
            this.CustomDatas = new HashSet<CustomData>();
            this.GroupCustomDataPages = new HashSet<GroupCustomDataPage>();
        }
    
        public int idGroup { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
    
        public virtual ICollection<CustomData> CustomDatas { get; set; }
        public virtual ICollection<GroupCustomDataPage> GroupCustomDataPages { get; set; }
    }
}
