//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modal
    {
        public Modal()
        {
            this.GroupModalPages = new HashSet<GroupModalPage>();
        }
    
        public int idModal { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime dtCreate { get; set; }
    
        public virtual ICollection<GroupModalPage> GroupModalPages { get; set; }
    }
}
