//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProduct
    {
        public PlanProduct()
        {
            this.PlanGroups = new HashSet<PlanGroup>();
            this.Prices = new HashSet<Price>();
        }
    
        public int idPlan { get; set; }
        public int idProduct { get; set; }
        public bool defaultSKU { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string linkEcommerce { get; set; }
        public bool isVisible { get; set; }
        public System.DateTime dtCreate { get; set; }
    
        public virtual ICollection<PlanGroup> PlanGroups { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
    }
}
