//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int idPrice { get; set; }
        public int idPlan { get; set; }
        public int idPriceGroup { get; set; }
        public int idPriceLoyalty { get; set; }
        public int idTypeClient { get; set; }
        public int idPaymentMethod { get; set; }
        public decimal value { get; set; }
        public Nullable<decimal> valueCombo { get; set; }
    
        public virtual PriceLoyalty PriceLoyalty { get; set; }
        public virtual PricePaymentMethod PricePaymentMethod { get; set; }
        public virtual PriceTypeClient PriceTypeClient { get; set; }
        public virtual PlanProduct PlanProduct { get; set; }
    }
}
