//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceTypeClient
    {
        public PriceTypeClient()
        {
            this.Prices = new HashSet<Price>();
        }
    
        public int idTypeClient { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Price> Prices { get; set; }
    }
}
