//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.PriceGroups = new HashSet<PriceGroup>();
            this.PriceGroupCities = new HashSet<PriceGroupCity>();
            this.PlanProducts = new HashSet<PlanProduct>();
        }
    
        public int idProduct { get; set; }
        public Nullable<int> idProductFamily { get; set; }
        public string name { get; set; }
        public bool isVisible { get; set; }
        public string valueGroupPrice { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
    
        public virtual ICollection<PriceGroup> PriceGroups { get; set; }
        public virtual ICollection<PriceGroupCity> PriceGroupCities { get; set; }
        public virtual ProductFamily ProductFamily { get; set; }
        public virtual ICollection<PlanProduct> PlanProducts { get; set; }
    }
}
