//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OiWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionAPI
    {
        public VersionAPI()
        {
            this.CustomDatas = new HashSet<CustomData>();
        }
    
        public int idVersion { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<CustomData> CustomDatas { get; set; }
    }
}
